### ISSUE TITLE
Erro ao enviar e-mail

### ISSUE THREAD

**Issue by jpmehl** [ethymos/sendpress#14]
Após concluir o e-mail e enviar a mensagem, no lugar do boletim, está aparecendo esta tela abaixo.
![captura de tela de 2014-08-11 16 23 42](https://cloud.githubusercontent.com/assets/4163139/3881322/09df8c78-218d-11e4-89be-fc6f3ec27f4b.png)

**Comment by jacsonp** [comment]
This issue was moved to redelivre/jaiminho#12
