### ISSUE TITLE
Relatórios

### ISSUE THREAD

**Issue by jpmehl** [ethymos/sendpress#27]
É possível visualizar quantas pessoas leram ou clicaram uma campanha, no entanto, não podemos fazer o download destes relatórios. 
Em "visão geral" aparecem os usuários "mais ativos", que pela observaçào supus que tem relação com leitura e cliques. 
Com isto, destaco a importância de uma área de relatórios.

**Comment by jacsonp** [comment]
This issue was moved to redelivre/jaiminho#5
